
services:
  # Telegram to Claude Bridge - receives messages from Telegram
  telegram-to-claude-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-claude-bridge
    ports:
      - "4041:4041"
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TG_CLAUDE_WEBHOOK_PORT=4041
      - WEBHOOK_BASE_URL=http://telegram-claude-bridge:4041
      - LOG_LEVEL=info
    volumes:
      - ./.env:/app/.env:ro
      - /tmp/claude-telegram-pipe:/tmp/claude-telegram-pipe
    command: ["npm", "run", "tg-claude-bridge"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4041/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - hermes-network

  # MCP proxy for Docker - enables Claude Code to communicate with Dockerized services
  mcp-docker-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-docker-proxy
    ports:
      - "4042:4042"
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MCP_PROXY_PORT=4042
      - HERMES_MCP_URL=http://hermes-mcp-server:4040
      - LOG_LEVEL=debug
    volumes:
      - ./.env:/app/.env:ro
      - /tmp/claude-telegram-pipe:/tmp/claude-telegram-pipe
    command: ["npm", "run", "mcp-proxy"]
    restart: unless-stopped
    networks:
      - hermes-network

networks:
  hermes-network:
    external: true